# -*- coding: utf-8 -*-
"""SocialSecurityTXTtoRandomName.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/193ZkwcRQ_6D264GHEt3XD_OCAyw1_q_I
"""

import csv
import random

names = input()  #Input the name of your txt file

#Opens names and stores it as string x
with open(names, "r") as file:
  x = file.read()

#Splits txt into list of name,sex,number units
y = x.split("\n")

#Splits y into three lists for name, sex, and number
z = [None]*(len(y)-1)
namelist = [None]*(len(y)-1)
sex = [None]*(len(y)-1)
number = [None]*(len(y)-1)
numbercdf = [None]*(len(y)-1)
for i in range(len(y)-1):
  z[i] = y[i].split(",")
  namelist[i] = z[i][0]
  sex[i] = z[i][1]
  number[i] = int(z[i][2])
  numbercdf[i] = sum(number[:i])

#Normalizes the numbercdf list
normcdf = [None]*(len(y)-1)
for i in range(len(numbercdf)):
  normcdf[i] = numbercdf[i]/sum(number)


length = 0
for i in sex:
  if i == "M":
    length = length + 1

#Creates list of male names
malenames = [None]*length
malenum = [None]*length
j = 0
for i in range(len(namelist)):
  if sex[i] == "M":
    malenames[j] = namelist[i]
    malenum[j] = number[i]
    j = j + 1

malenumcdf = [None]*length
for i in range(len(malenum)):
  malenumcdf[i] = sum(malenum[:i])

#Normalizes the malenumcdf list
malenormcdf = [None]*length
for i in range(len(malenum)):
  malenormcdf[i] = malenumcdf[i]/sum(malenum)


length = 0
for i in sex:
  if i == "F":
    length = length + 1

#Creates list of female names
femalenames = [None]*length
femalenum = [None]*length
j = 0
for i in range(len(namelist)):
  if sex[i] == "F":
    femalenames[j] = namelist[i]
    femalenum[j] = number[i]
    j = j + 1

femalenumcdf = [None]*length
for i in range(len(femalenum)):
  femalenumcdf[i] = sum(femalenum[:i])

#Normalizes the femalenumcdf list
femalenormcdf = [None]*length
for i in range(len(femalenum)):
  femalenormcdf[i] = femalenumcdf[i]/sum(femalenum)

#Random name
rand = random.random()

count = [None]*len(normcdf)
item = 0
for i in range(len(normcdf)):
  if normcdf[i] < rand:
    item = item + 1

if sex[item] == "M":
  print("Male name of rank " + str(item) + ": " + namelist[item])
else:
  print("Female name of rank " + str(item) + ": " + namelist[item])

#Random male name
rand = random.random()

count = [None]*len(malenormcdf)
item = 0
for i in range(len(malenormcdf)):
  if malenormcdf[i] < rand:
    item = item + 1

print("Male name of rank " + str(item) + ": " + malenames[item])

#Random female name
rand = random.random()

count = [None]*len(femalenormcdf)
item = 0
for i in range(len(femalenormcdf)):
  if femalenormcdf[i] < rand:
    item = item + 1

print("Female name of rank " + str(item) + ": " + femalenames[item])

#Random top ___ name

rank = input()

a = normcdf[int(rank)]

#Normalizes the numbercdf list
newnorm = [None]*len(normcdf)
for i in range(len(normcdf)):
  newnorm[i] = normcdf[i]/a

rand = random.random()

count = [None]*len(newnorm)
item = 0
for i in range(len(newnorm)):
  if newnorm[i] < rand:
    item = item + 1

if sex[item] == "M":
  print("Male name of rank " + str(item) + ": " + namelist[item])
else:
  print("Female name of rank " + str(item) + ": " + namelist[item])